### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by joaoquinto** [joaoquinto/joaoquinto-portfolio#3]
# Assets

## Cores 
- [x] Cor background - #393131
- [x] Cor backgroun header - #322B2B
- [x] Cor de botões - #FFFFF
- [x] Cor de corpo Texto - #FFFFF
- [x] Cor de texto botões  - #393131
- [x] Cor background card - #5E585C

## Font Family
- [x] Fonte de Título - Montserrat - Bold 700
- [x] Fonte de corpo - Raleway - Regular 400

## Font size
- [x]  Fonte de Título - 30px
- [x] Fonte de corpo - 20~16px
- [x] Fonte de botões - 20px

## Imagens

- [x] Ícone de perfil
- [x] Ícone HTML
- [x] Ícone CSS
- [x] Ícone MYSQL
- [x] Ícone GIT
- [x] Google Analytics
- [x] Adobe XD
